spring:
  cloud:
    loadbalancer:
        retry: 
            enabled: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 8000
    connect-timeout-millis: 8000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:
      path: /uac/**
      sensitiveHeaders:
#      strip-prefix: false
      service-id: dractivitytreasure-provider-uac
    amc-route:
      path: /amc/**
      sensitiveHeaders:
      service-id: dractivitytreasure-provider-amc
  add-proxy-headers: true
  add-host-header: true
  
dractivitytreasure-provider-uac:
  ribbon:
    eager-load:
      enabled: true
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true
    ConnectTimeout: 8000
    ReadTimeout: 8000
        
dractivitytreasure-provider-amc:
  ribbon:        
    eager-load:
      enabled: true
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: false
    ConnectTimeout: 30000
    ReadTimeout: 30000

security:
  oauth2:
    client:
      clientId: dractivitytreasure-client-gateway
      clientSecret: dractivitytreasureClientSecret
      access-token-uri: http://dractivitytreasure-gateway:7979/uac/oauth/token
      user-authorization-uri: http://dractivitytreasure-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://dractivitytreasure-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://dractivitytreasure-provider-uac:8000/oauth/token_key

proxy:
  auth:
    routes:
      uac-route: oauth2
      mdc-route: oauth2

dractivitytreasure:
  enableSqlLogInterceptor: false
# swagger butler配置
swagger.butler:
  api-docs-path: v2/api-docs
  swagger-version: 1.0
  auto-generate-from-zuul-routes: true
# 指定要生成的范围
  generate-routes: omc-route,mdc-route,opc-route,tpc-route,uac-route
# 忽略某些路由生成
#  ignore-routes:
