spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://192.168.51.8:3306/huodongbao?characterEncoding=utf8&useSSL=false

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.paascloud.provider.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.dractivitytreasure.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: dractivitytreasure-client-amc
      clientSecret: paascloudClientSecret
      access-token-uri: http://192.168.51.14:7979/uac/oauth/token
      user-authorization-uri: http://192.168.51.14:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://192.168.51.14:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://192.168.51.14:8000/oauth/token_key

dractivitytreasure:
  enableSqlLogInterceptor: false
  aliyun:
    rocketMq:
      enable: false
      reliableMessageConsumer: false
      reliableMessageProducer: false
      instanceName: dractivitytreasure-provider-amc
      consumerGroup: CID_OMC
      producerGroup: PID_OMC
  token:
    interceptor:
      enable: true
  zk:
    zkAddressList: dractivitytreasure-provider-zk:2181
  oauth2:
    jwtSigningKey: dractivitytreasure
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
  alipay:
    callback:
      url: http://api.dractivitytreasure.net/omc/pay/alipayCallback
    qrCode:
      pcPath: E:/File/alipay/QRCode
      qiniuPath: alipay/QRCode/